// Washington State Department of Revenue two-digit land use codes (WAC 458-53-030).
// Used to decode LANDUSE_CD on the statewide parcel layer and the leading two digits of
// county use codes that follow the DOR scheme (e.g. Pierce County's four-digit codes).
export const DOR_LAND_USE = {
  11: 'Household, single family units',
  12: 'Household, 2-4 units',
  13: 'Household, multi-units (5 or more)',
  14: 'Residential condominiums',
  15: 'Mobile home parks or courts',
  16: 'Hotels/motels',
  17: 'Institutional lodging',
  18: 'All other residential not elsewhere coded',
  19: 'Vacation and cabin',
  21: 'Food and kindred products',
  22: 'Textile mill products',
  23: 'Apparel and other finished products',
  24: 'Lumber and wood products (except furniture)',
  25: 'Furniture and fixtures',
  26: 'Paper and allied products',
  27: 'Printing and publishing',
  28: 'Chemicals',
  29: 'Petroleum refining and related industries',
  30: 'Rubber and miscellaneous plastic products',
  31: 'Leather and leather products',
  32: 'Stone, clay and glass products',
  33: 'Primary metal industries',
  34: 'Fabricated metal products',
  35: 'Professional, scientific and controlling instruments; photographic and optical goods',
  39: 'Miscellaneous manufacturing',
  41: 'Railroad/transit transportation',
  42: 'Motor vehicle transportation',
  43: 'Aircraft transportation',
  44: 'Marine craft transportation',
  45: 'Highway and street right of way',
  46: 'Automobile parking',
  47: 'Communication',
  48: 'Utilities',
  49: 'Other transportation, communication and utilities',
  50: 'Condominiums, other than residential',
  51: 'Wholesale trade',
  52: 'Retail trade: building materials, hardware and farm equipment',
  53: 'Retail trade: general merchandise',
  54: 'Retail trade: food',
  55: 'Retail trade: automotive, marine craft, aircraft and accessories',
  56: 'Retail trade: apparel and accessories',
  57: 'Retail trade: furniture, home furnishings and equipment',
  58: 'Retail trade: eating and drinking',
  59: 'Other retail trade',
  61: 'Finance, insurance and real estate services',
  62: 'Personal services',
  63: 'Business services',
  64: 'Repair services',
  65: 'Professional services (medical, dental, etc.)',
  66: 'Contract construction services',
  67: 'Governmental services',
  68: 'Educational services',
  69: 'Miscellaneous services',
  71: 'Cultural activities and nature exhibitions',
  72: 'Public assembly',
  73: 'Amusements',
  74: 'Recreational activities',
  75: 'Resorts and group camps',
  76: 'Parks',
  79: 'Other cultural, entertainment and recreational',
  81: 'Agriculture (not classified under current use law)',
  82: 'Agriculture related activities',
  83: 'Agriculture classified under current use (RCW 84.34)',
  84: 'Fishing activities and related services',
  85: 'Mining activities and related services',
  88: 'Designated forest land (RCW 84.33)',
  89: 'Other resource production',
  91: 'Undeveloped land (land only)',
  92: 'Noncommercial forest',
  93: 'Water areas',
  94: 'Open space land classified under RCW 84.34',
  95: 'Timberland classified under RCW 84.34',
  99: 'Other undeveloped land',
};

/** Decodes a DOR code (or a longer county code whose first two digits follow DOR). */
export function decodeDOR(code) {
  if (code === null || code === undefined || code === '') return '';
  const digits = String(code).replace(/\D/g, '');
  if (!digits) return '';
  const two = Number(digits.slice(0, 2));
  return DOR_LAND_USE[two] || '';
}
